# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11d5c34e19dd0c5cefe4fd2ff0d45fa1c58be4d789c3da5f4400f9c4647ab0e4b142e0bc58d81172343e248d52b7ac5735c5408e55d3e7f41901e9b475081408

test:
  secret_key_base: 35ae2413d7f3f3d16c8bd100f7342a7432e9efd30c96b0a630eb217c1eb8168206e009df14382e2b2360336e78eca0dbdc12975cb0652ba24ce586148fab8dc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
